GET http://localhost:5138/ping

###
GET http://localhost:5138/games

###
GET http://localhost:5138/games/4

###
POST http://localhost:5138/games
Content-Type: application/json

{
  "name": "Street Fighter II",
  "genreId": 1,
  "price": 39.90,
  "releaseDate": "1991-02-06"
}

###
PUT http://localhost:5138/games/4
Content-Type: application/json

{
  "name": "Street Fighter II (ATUALIZADO)",
  "genreId": 1,
  "price": 39.90,
  "releaseDate": "1991-02-06"
}

###
DELETE http://localhost:5138/games/2
