# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: Inventory
services:  
  app:
    language: dotnet
    project: ./src/Inventory.AppHost/Inventory.AppHost.csproj
    host: containerapp
